# Generated by Django 4.2.13 on 2024-06-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_client_service_alter_client_appointmentdt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='service',
            field=models.CharField(max_length=200, verbose_name='Service'),
        ),
    ]
